# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 391aa57ff4dd652b7b9aa314d87575c2bb986d4d304909bf2118b7c85729e10a656ad38b803c2e042e1f8625d9f014ff6cdd7788047bd37c30e01bbaad6f726a

test:
  secret_key_base: eeb8be98913627c411ce88a4e73b0b5845c3596186cf52765bd239aae44d40bd3e0db904cce203bdaf32f423317d7e3b87832a12b3f8a4b569092f0e56974bbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
